defaults:
  - _self_
  - model: enetv2s
  - criterion: ce

img_size: 224
batch_size: 32
num_workers: 0

max_epochs: 100

csv_file: "/repo/tta_class/data/dataset.csv"
img_dir: "/repo/tta_class/data/images"
